/* lib/flags.js — Maps team names to ISO 3166-1 alpha-2 country codes for flagcdn.com */

const TEAM_TO_CODE = {
  // CONCACAF
  'mexico': 'mx',
  'canada': 'ca',
  'united states': 'us',
  'usa': 'us',
  'us': 'us',
  'panama': 'pa',
  'haiti': 'ht',
  'curacao': 'cw',
  'curaçao': 'cw',
  'honduras': 'hn',
  'jamaica': 'jm',
  'el salvador': 'sv',
  'guatemala': 'gt',
  'trinidad and tobago': 'tt',
  'costa rica': 'cr',
  'suriname': 'sr',

  // CONMEBOL
  'argentina': 'ar',
  'brazil': 'br',
  'colombia': 'co',
  'ecuador': 'ec',
  'uruguay': 'uy',
  'paraguay': 'py',
  'bolivia': 'bo',
  'chile': 'cl',
  'peru': 'pe',
  'venezuela': 've',

  // UEFA
  'spain': 'es',
  'portugal': 'pt',
  'france': 'fr',
  'germany': 'de',
  'netherlands': 'nl',
  'england': 'gb-eng',
  'belgium': 'be',
  'switzerland': 'ch',
  'austria': 'at',
  'croatia': 'hr',
  'italy': 'it',
  'norway': 'no',
  'czechia': 'cz',
  'czech republic': 'cz',
  'sweden': 'se',
  'turkey': 'tr',
  'türkiye': 'tr',
  'turkiye': 'tr',
  'bosnia-herzegovina': 'ba',
  'bosnia and herzegovina': 'ba',
  'bosnia & herzegovina': 'ba',
  'denmark': 'dk',
  'poland': 'pl',
  'scotland': 'gb-sct',
  'wales': 'gb-wls',
  'ireland': 'ie',
  'serbia': 'rs',
  'ukraine': 'ua',
  'romania': 'ro',
  'hungary': 'hu',
  'slovenia': 'si',
  'slovakia': 'sk',
  'albania': 'al',
  'greece': 'gr',
  'finland': 'fi',
  'iceland': 'is',
  'kosovo': 'xk',
  'montenegro': 'me',
  'north macedonia': 'mk',
  'azerbaijan': 'az',
  'belarus': 'by',

  // AFC
  'japan': 'jp',
  'south korea': 'kr',
  'korea republic': 'kr',
  'iran': 'ir',
  'australia': 'au',
  'saudi arabia': 'sa',
  'jordan': 'jo',
  'uzbekistan': 'uz',
  'qatar': 'qa',
  'iraq': 'iq',
  'china': 'cn',
  'thailand': 'th',
  'vietnam': 'vn',
  'indonesia': 'id',
  'malaysia': 'my',
  'philippines': 'ph',
  'india': 'in',
  'syria': 'sy',
  'oman': 'om',
  'kuwait': 'kw',
  'bahrain': 'bh',
  'lebanon': 'lb',
  'palestine': 'ps',
  'tajikistan': 'tj',
  'turkmenistan': 'tm',
  'kyrgyzstan': 'kg',
  'kazakhstan': 'kz',
  'north korea': 'kp',
  'korea dpr': 'kp',
  'united arab emirates': 'ae',
  'uae': 'ae',

  // CAF
  'morocco': 'ma',
  'senegal': 'sn',
  'egypt': 'eg',
  'tunisia': 'tn',
  'algeria': 'dz',
  'ghana': 'gh',
  'south africa': 'za',
  'cape verde': 'cv',
  'cape verde islands': 'cv',
  'dr congo': 'cd',
  'congo dr': 'cd',
  'democratic republic of the congo': 'cd',
  'nigeria': 'ng',
  'cameroon': 'cm',
  'ivory coast': 'ci',
  "côte d'ivoire": 'ci',
  "cote d'ivoire": 'ci',
  'mali': 'ml',
  'burkina faso': 'bf',
  'angola': 'ao',
  'guinea': 'gn',
  'kenya': 'ke',
  'uganda': 'ug',
  'zambia': 'zm',
  'zimbabwe': 'zw',
  'tanzania': 'tz',
  'mozambique': 'mz',
  'gabon': 'ga',
  'libya': 'ly',
  'sudan': 'sd',
  'ethiopia': 'et',
  'rwanda': 'rw',
  'namibia': 'na',
  'botswana': 'bw',
  'congo': 'cg',
  'benin': 'bj',
  'togo': 'tg',
  'sierra leone': 'sl',
  'mauritania': 'mr',
  'gambia': 'gm',
  'liberia': 'lr',
  'eritrea': 'er',
  'central african republic': 'cf',
  'comoros': 'km',
  'madagascar': 'mg',
  'malawi': 'mw',
  'lesotho': 'ls',
  'eswatini': 'sz',
  'burundi': 'bi',
  'somalia': 'so',
  'south sudan': 'ss',
  'mauritius': 'mu',
  'sao tome and principe': 'st',
  'equatorial guinea': 'gq',
  'djibouti': 'dj',
  'chad': 'td',
  'niger': 'ne',
  'guinea-bissau': 'gw',

  // OFC
  'new zealand': 'nz',
  'new caledonia': 'nc',
  'fiji': 'fj',
  'tahiti': 'pf',
  'solomon islands': 'sb',
  'vanuatu': 'vu',
  'papua new guinea': 'pg',
};

function normalize(name) {
  return (name || '').toString().trim().toLowerCase();
}

export function getFlagCode(teamName) {
  return TEAM_TO_CODE[normalize(teamName)] || null;
}

/* Returns an <img> tag for the team flag, or empty string if no mapping found.
 * width: width hint for flagcdn (16, 20, 40, 80, 160, 320, etc) */
export function flagImg(teamName, width = 40, className = 'team-flag') {
  const code = getFlagCode(teamName);
  if (!code) return '';
  const url = `https://flagcdn.com/w${width}/${code}.png`;
  const url2x = `https://flagcdn.com/w${width * 2}/${code}.png`;
  return `<img src="${url}" srcset="${url2x} 2x" alt="${teamName}" class="${className}" loading="lazy" decoding="async">`;
}
